repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        files: '(.*\.py|(src|tests|docs)/(.*/)*.*\.py)'
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    -   id: isort
        files: '(.*\.py|(src|tests|docs)/(.*/)*.*\.py)'
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        files: '(.*\.py|(src|tests|docs)/(.*/)*.*\.py)'
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    -   id: mypy
        files: '(.*\.py|(src|tests|docs)/(.*/)*.*\.py)'
        args: [--no-strict-optional, --ignore-missing-imports]
