repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    -   id: isort
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
        files: ^(src|tests)/(.*/)*.*\.py$
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    -   id: mypy
        files: ^(.*\.py|(src|tests|docs)/(.*/)*.*\.py)$
        exclude: ^tests/(.*/)*ref_.*.py$
        args: [--no-strict-optional, --ignore-missing-imports, --pretty]
        additional_dependencies:
        -   "pydantic"
