
[flake8]
exclude = docs
max-line-length = 88
ignore =
    E203, # Allow whitespace before ':'
          # See https://github.com/PyCQA/pycodestyle/issues/373
    W503, # Allow line break before binary operator (PEP 8-compatible)

[pytest]
collect_ignore = ["setup.py"]
testpaths = tests
addopts =
    -s
    -rs
    --color=no

[tox]
envlist =
    py37
    flake8

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
install_command =
    pip install -U {opts} {packages}
deps =
    pytest
# If you want tox to use pinned package versions, create a requirements.txt
# (`pipenv freeze`) and uncomment the following line:
#    -r{toxinidir}/requirements.txt
commands =
    pytest --basetemp={envtmpdir} --junitxml=junit-{envname}.xml

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 src tests

